spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/PMA_DB
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # You can use "create" for development, but be careful in production.
    show-sql: true # Set to true for debugging, false in production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

